# 端口号配置
server:
  port: 9082

spring:
  application:
    name: order-server
  datasource:
    url: jdbc:mysql://localhost:3306/gientech-work-order?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    timeout: 5000
    database: 0
    cluster:
      nodes: localhost:7000,localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005
      max-redirects: 3
    lettuce:
      pool:
        max-total: 12
        # 最大活跃链接数 默认8（使用负值表示没有限制）
        max-active: 12
        # 最大空闲连接数 默认8
        max-idle: 12
        # 最小空闲连接数 默认0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  cloud:  #nacos注册中心地址的配置法
    nacos:
      discovery:
        server-addr: localhost:8848

#rocketmq配置信息
rocketmq:
  #nameservice服务器地址（多个以英文逗号隔开）
  name-server: 127.0.0.1:9876